"""empty message

Revision ID: 32d8218defbd
Revises: None
Create Date: 2013-12-07 15:49:54.597199

"""

# revision identifiers, used by Alembic.
revision = '32d8218defbd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weights',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('goal_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('weights')
    ### end Alembic commands ###
