"""empty message

Revision ID: 3508973368c4
Revises: 32d8218defbd
Create Date: 2014-01-13 22:59:02.627029

"""

# revision identifiers, used by Alembic.
revision = '3508973368c4'
down_revision = '32d8218defbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derived_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derived_positions')
    ### end Alembic commands ###
